SELECT
CAB.NUNOTA,
CAB.CODPARC,
PAR.NOMEPARC,
COUNT (DISTINCT(ITE.CODPROD)) “CONTADORITENS”
FROM TGFCAB CAB, TGFITE ITE, TGFPRO PRO, TGFPAR PAR
WHERE CAB.TIPMOV = ‘V’
AND ITE.CODPROD = PRO.CODPROD
AND CAB.CODPARC = PAR.CODPARC
AND CAB.NUNOTA = ITE.NUNOTA 
GROUP BY CAB.NUNOTA, CAB.CODPARC,PAR.NOMEPARC
ORDER BY CAB.NUNOTA DESC