CREATE OR REPLACE VIEW  VGFCAB_GRD_VDA
AS
  SELECT CAB.NUNOTA, CAB.CODPARC,PAR.NOMEPARC,
               COUNT (DISTINCT(ITE.CODPROD)) CONTADORITENS
   FROM TGFCAB CAB, TGFITE ITE, TGFPRO PRO, TGFPAR PAR
   WHERE CAB.TIPMOV = 'V'
           AND ITE.CODPROD = PRO.CODPROD
           AND CAB.CODPARC = PAR.CODPARC
           AND CAB.NUNOTA = ITE.NUNOTA 
GROUP BY CAB.NUNOTA, CAB.CODPARC,PAR.NOMEPARC
   HAVING COUNT(DISTINCT (ITE.CODPROD)) >3
ORDER BY CAB.NUNOTA DESC 
WITH READ ONLY